language: cpp
dist: bionic

addons:
  apt:
    packages:
      - qt5-default
      - qt5-qmake

matrix:
  include:
    - compiler: gcc
      env: QMAKESPEC=linux-g++
    - compiler: clang
      env: QMAKESPEC=linux-clang

script:
  - qmake -qt=qt5
  - make
